### ISSUE TITLE
Background

### ISSUE THREAD

**Issue by Erhannis** [olesk75/AnimatedGIF#2]
Well, it certainly works better than anything else I've seen (since I've not found anything else that works).  It doesn't render some gifs right, though; like, I think some gifs only update the part of the frame that changed.  AnimatedGif only displays that part (and the rest is grey).

**Comment by olesk75** [comment]
Yeah, it’s unfortunately a known problem, which is a limitation of the external library used to display GIFs (which is not really fantastic). This is one of the reasons why I migrated to Qt a while after I made this module. Qt is infinitely more feature rich and more robust, but it’s quite overkill for the kind of stuff one would apply Tk to in most cases…

If you need to a) stay with Tk and b) need more robust GIF rendering, I’d consider making my own GIF renderer instead of using Tk. But that might be more work than you want to sink into this. So perhaps the easier route is to make/remake GIFs that update the entire frame. 

Admittedly, Tk is not really designed to show threaded animated gifs, so I’ll be the first to admit that my solution is at best a workaround for limited cases.
